### ISSUE TITLE
could not retrieve current WAN address from http://www.myip.ch

### ISSUE THREAD

**Issue by ogezue** [kaimi/inwx-dns-updater#4]
Hi, what could be the problem with your script?

bash inwx-dns-updater.sh 
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
    [-e pattern] [-f file] [--binary-files=value] [--color=when]
    [--context[=num]] [--directories=action] [--label] [--line-buffered]
    [--null] [pattern] [file ...](23) Failed writing body
ERROR: could not retrieve current WAN address from http://www.myip.ch.

**Comment by kaimi** [comment]
Sounds like a connection issue to me. Hard to say without more debug output, which I unfortunately couldn’t be arsed to build into the script ;)

I guess that’s not a persistent issue? If it is, try running `curl -sf http://www.myip.ch` in a terminal. A “normal” result would look like this:

``` html
<html>
<head>
<title>Current IP Check</title>
</head>
<body>
Current IP Address: xxx.xxx.xxx.xxx<br/><br/>
Powered by <a href="http://www.microsolutions.ch">Micro Solutions AG</a>
</body>
</html>
```

Side note, I’m kinda surprised that someone else uses this. Hope it helped. Free software rules :)

**Comment by kaimi** [comment]
I should probably restrict the `curl` call to IPv4. The site only runs on v4 at the moment, but who knows if it might change in the future …

**Comment by kaimi** [comment]
… aaaand #5.

Sorry for spamming you with notification emails :<

**Comment by ogezue** [comment]
Mhh - I still get the result

(23) Failed writing body
ERROR: could not retrieve current WAN address from http://www.myip.ch.

But the curl for myip works as you suggest.

**Comment by ogezue** [comment]
Perhaps I'm using the wrong configuration. What I want to archieve is to change the IP for nas.mydomain.name. Previously I had "nas.mydomain.name" set as the hostname. Now I changed it to "mydomain.name" and I'm getting the error
ERROR: could not retrieve DNS entry for mydomain.name from ns.inwx.de.

**Comment by kaimi** [comment]
> Mhh - I still get the result
> 
> (23) Failed writing body
> ERROR: could not retrieve current WAN address from http://www.myip.ch.

That’s … weird. `curl` error 23 indicates a problem writing to its output … which is just piped into `grep`. Can you run the full line in question `curl -sf http://www.myip.ch | grep -Po '(\d+\.){3}\d+'` in a terminal? Preferrably on the same machine as the script runs on.

**Comment by kaimi** [comment]
> Previously I had "nas.mydomain.name" set as the hostname. Now I changed it to "mydomain.name" and I'm getting the error
> ERROR: could not retrieve DNS entry for mydomain.name from ns.inwx.de.

Are you sure you have configured a DNS entry for mydomain.name in addition to nas.mydomain.name? Can’t test it from here of course if I don’t have the real domain name :)

**Comment by ogezue** [comment]
I thing so. I have an entry for "*",  blank and "www" of type A.

**Comment by kaimi** [comment]
I’m just going to assume this is no longer an issue :)
